version: 2

generic:
  - &job_config
    docker:
      - image: circleci/android:api-28-alpha
    working_directory: ~/repo
    environment:
      _JAVA_OPTIONS: "-Xms512m -Xmx1024m"
      GRADLE_OPTS: -Dorg.gradle.daemon=false

  - &attach_workspace
    attach_workspace:
      at: ~/

experimental:
  notify:
    branches:
      only:
        - develop
        - master
        - /.*release.*/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - assemble-deploy-snapshot:
          requires:
            - build
          filters:
            branches:
              ignore:
                - /.*release.*/
                - master
      - assemble-deploy-qa:
          requires:
            - build
          filters:
            branches:
              only: /.*release.*/
      - assemble-deploy-release:
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  build:
    <<: *job_config
    steps:
      - run:
          name: Setup AWS CLI
          command: sudo pip install awscli
      - checkout
      - run:
          name: Write gradle.properties
          command: /bin/bash writegradleprops.sh
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "dependencies.gradle" }}
      - run:
          name: Download Android Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.android
          key: v2-dependencies-{{ checksum "dependencies.gradle" }}
      - run:
          name: Test
          command: ./gradlew clean lint test
      - persist_to_workspace:
          root: ~/
          paths:
            - repo
            - .gradle
            - .android
      # ********************************************
      # Insert test artifacts to upload
      # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
      - store_artifacts:
          path: enabled-device-api/build/reports
      # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

  assemble-deploy-snapshot:
    <<: *job_config
    steps:
      - *attach_workspace
      # ********************************************
      # Define tasks to run on normal branches
      # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
      - run: ./gradlew assembleDebug
      - store_artifacts:
          path: enabled-device-api/build/libs
      # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

  assemble-deploy-qa:
    <<: *job_config
    steps:
      - *attach_workspace
      # ********************************************
      # Define tasks to run on qa branches (release/*)
      # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
      - run: ./gradlew jar assembleRelease publishApiJarPublicationToQaRepository publishReleasePublicationToQaRepository
      # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

  assemble-deploy-release:
    <<: *job_config
    steps:
      - *attach_workspace
      # ********************************************
      # Define tasks to run on master branch
      # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
      - run: ./gradlew jar assembleRelease publishApiJarPublicationToReleaseRepository publishReleasePublicationToReleaseRepository bintrayUpload
      # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
