name: Android CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Hopefully we won't need to keep this for long (see: https://github.com/actions/checkout/issues/287)
      - name: Clone gradle-scripts
        uses: actions/checkout@v2
        with:
          repository: Aevi-UK/gradle-scripts
          path: gradle-scripts
          ssh-key: ${{ secrets.GRADLE_SCRIPTS_CHECKOUT_KEY }}
      - name: Check out gradle-scripts
        run: |
          git submodule init
          git submodule update
      # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('dependencies.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and test
        run: |
          ./gradlew test jar assembleRelease

      - name: Publish release
        if: github.ref == 'refs/heads/master'
        run: ./gradlew publishJavaPublicationToGithubRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}